import argparse
import csv
import json
import os
from glob import glob
from typing import Any, Dict, List


def read_json(path: str) -> Dict[str, Any]:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def collect_manifests(result_root: str) -> List[str]:
    return sorted(glob(os.path.join(result_root, "*", "manifest.json")))


def extract_row(manifest_path: str) -> Dict[str, Any]:
    manifest = read_json(manifest_path)

    summary_data = {}
    summary_path = manifest.get("summary_json", "")
    if summary_path and os.path.exists(summary_path):
        payload = read_json(summary_path)
        summary_data = payload.get("summary", {})

    risk = summary_data.get("risk_levels", {}) if isinstance(summary_data, dict) else {}

    processed = int(summary_data.get("processed", 0)) if isinstance(summary_data, dict) else 0
    high = int(risk.get("high", 0))
    medium = int(risk.get("medium", 0))
    low = int(risk.get("low", 0))

    high_rate = (high / processed) if processed else 0.0

    return {
        "experiment": manifest.get("experiment", ""),
        "return_code": manifest.get("return_code", -1),
        "duration_sec": manifest.get("duration_sec", 0.0),
        "processed": processed,
        "high": high,
        "medium": medium,
        "low": low,
        "high_rate": round(high_rate, 6),
        "event_segments": summary_data.get("event_segments", 0) if isinstance(summary_data, dict) else 0,
        "run_jsonl": manifest.get("run_jsonl", ""),
        "summary_json": manifest.get("summary_json", ""),
        "manifest_path": manifest_path,
    }


def write_csv(rows: List[Dict[str, Any]], output_csv: str) -> None:
    if not rows:
        return

    fieldnames = [
        "experiment",
        "return_code",
        "duration_sec",
        "processed",
        "high",
        "medium",
        "low",
        "high_rate",
        "event_segments",
        "run_jsonl",
        "summary_json",
        "manifest_path",
    ]

    with open(output_csv, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def write_markdown(rows: List[Dict[str, Any]], output_md: str) -> None:
    lines = []
    lines.append("# Suite Summary")
    lines.append("")
    lines.append("| experiment | rc | duration(s) | processed | high | medium | low | high_rate | event_segments |")
    lines.append("|---|---:|---:|---:|---:|---:|---:|---:|---:|")

    for row in rows:
        lines.append(
            "| {experiment} | {return_code} | {duration_sec} | {processed} | {high} | {medium} | {low} | {high_rate} | {event_segments} |".format(
                **row
            )
        )

    with open(output_md, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main() -> None:
    parser = argparse.ArgumentParser(description="Summarize suite manifests")
    parser.add_argument("--result-root", required=True, help="Result root generated by run_suite.py")
    parser.add_argument("--output-csv", default="", help="Output csv path")
    parser.add_argument("--output-md", default="", help="Output markdown path")
    args = parser.parse_args()

    manifests = collect_manifests(args.result_root)
    rows = [extract_row(path) for path in manifests]

    rows.sort(key=lambda r: (int(r["return_code"]), -int(r["processed"]), str(r["experiment"])))

    output_csv = args.output_csv or os.path.join(args.result_root, "suite_summary.csv")
    output_md = args.output_md or os.path.join(args.result_root, "suite_summary.md")

    write_csv(rows, output_csv)
    write_markdown(rows, output_md)

    print(f"[SUMMARY] rows={len(rows)}")
    print(f"[SUMMARY] csv={output_csv}")
    print(f"[SUMMARY] md={output_md}")


if __name__ == "__main__":
    main()
